### PR TITLE
src/cpu/x86/mp_init.c: Wait for APs to finish parking

### LINKED ISSUE #1428: MTL laptops hang at Restarting 21 APs
### Component

Dasharo firmware

### Device

NovaCustom V54 14th Gen, NovaCustom V56 14th Gen, NovaCustom NUC BOX 14th Gen

### Dasharo version

v1.0.0-rc3

### Dasharo Tools Suite version

any

### Test case ID

_No response_

### Brief summary

When booting with serial debug enabled, the platform frequently hangs at the `Attempting to start 21 APs` stage. This is reproducible and appears to be tied to recent CBnT changes and how APs are handled during restart.

### How reproducible

~75%

### How to reproduce

1. Enable serial debug output.
2. Reboot a couple times
3. Observe that the system hangs after reboot at `Attempting to start 21 APs`.

### Expected behavior

The platform boots

### Actual behavior

It hangs

### Screenshots

_No response_

### Additional context

**Possible root causes:**

* The issue is related to how CBnT code utilizes coreboot's SMP functions.
* `restart_aps()` is called without ensuring that all APs are fully idle.
* With debug enabled, APs contend for a serial spinlock, introducing a race condition where the BSP may INIT an AP while it's still printing debug info.
* This leads to an inconsistent state and causes the hang.
* Disabling serial debug output avoids the hang, confirming it's a timing/race condition issue.

### Solutions you've tried

**Proposed Solution:**

* Rework `park_this_cpu()` and `restart_aps()` to introduce a proper synchronization mechanism ensuring all APs are fully idle before continuing.
* Possibly add a completion-reporting mechanism to `park_this_cpu()` to avoid racing with INIT signals.
* Consider deferring AP restarts until all APs signal readiness.

### PR DESCRIPTION
**Pull request by mkopec**
Change-Id: Ic358e9750152881f4b965b94fb1103411f0df30c

Fixes https://github.com/Dasharo/dasharo-issues/issues/1428

### CODE REVIEW

**Comment by mkopec** [comment]
Works as intended, APs mp_park_aps will now wait for completion before returning:

```
[DEBUG]  CPU 8 going down...
[DEBUG]  CPU 64 going down...
[DEBUG]  CPU 40 going down...
[DEBUG]  CPU 66 going down...
[DEBUG]  CPU 57 going down...
[DEBUG]  CPU 12 going down...
[DEBUG]  CPU 4 going down...
[DEBUG]  CPU 0 going down...
[DEBUG]  CPU 17 going down...
[DEBUG]  CPU 41 going down...
[DEBUG]  CPU 25 going down...
[DEBUG]  CPU 2 going down...
[DEBUG]  CPU 6 going down...
[DEBUG]  CPU 24 going down...
[DEBUG]  CPU 49 going down...
[DEBUG]  CPU 33 going down...
[DEBUG]  CPU 14 going down...
[DEBUG]  CPU 48 going down...
[DEBUG]  CPU 56 going down...
[DEBUG]  CPU 10 going down...
[DEBUG]  CPU 16 going down...
[DEBUG]  mp_park_aps done after 79 msecs.
```

File: src/cpu/x86/lapic/lapic_cpu_stop.c [hunk 1]
```diff
@@ -55,6 +55,8 @@ void stop_this_cpu(void)
 
 	printk(BIOS_DEBUG, "CPU %ld going down...\n", id);
 
+	atomic_inc(&parked_ap_count);
```
Comment (SergiiDmytruk) [inline src/cpu/x86/lapic/lapic_cpu_stop.c:63]: This needs a comment explaining why the increment is done in this particular place and not above or below.

Comment (mkopec) [reply src/cpu/x86/lapic/lapic_cpu_stop.c:63]: Added a comment

**Review by SergiiDmytruk — APPROVED** [review]

**Review by filipleple — APPROVED** [review]

**Comment by filipleple** [comment]
Hm, had some trouble trying to fast forward and merge, will try again tomorrow:

```
Switched to branch 'dasharo'
Updating a881e941fe4b..c63d0cf19dc9
Fast-forward
 src/cpu/x86/lapic/lapic_cpu_stop.c |  7 +++++++
 src/cpu/x86/mp_init.c              | 16 ++++++++++++++++
 src/include/cpu/x86/lapic.h        |  3 +++
 3 files changed, 26 insertions(+)
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
remote: error: GH006: Protected branch update failed for refs/heads/dasharo.
remote:
remote: - Changes must be made through a pull request.
To https://github.com/Dasharo/coreboot
 ! [remote rejected]           dasharo -> dasharo (protected branch hook declined)
error: failed to push some refs to 'https://github.com/Dasharo/coreboot'
Failed to push branch dasharo
```

**Comment by SergiiDmytruk** [comment]
> had some trouble trying to fast forward and merge

CI for this PR was probably still running after you had pushed the rebased branch.
